### ISSUE TITLE
Latest changes break compatibility with stable version of projectile

### ISSUE THREAD

**Issue by DamienCassou** [NicolasPetton/amd-mode.el#9]
[This change](https://github.com/NicolasPetton/amd-mode.el/commit/d4396b72bd64ed6387be709e741b60f6434b062f#diff-cbed9aa7ffe6543e39332b37be5aa6f9R240) doesn't work with current stable version of projectile:

```diff
@@ -237,7 +237,7 @@ Also appends the filename to the modules list."
     (let ((file (projectile-completing-read
                  "Import file: "
                  (projectile-current-project-files)
-                 (concat (symbol-name (symbol-at-point)) ".js"))))
+                 :initial-input (concat (symbol-name (symbol-at-point)) ".js"))))
       (amd--import file))))
 
 (defun amd-rename-file ()
@@ -517,7 +517,7 @@ Note: This function is mostly a copy/paste from
   (let ((file (projectile-completing-read
                 "Find file: "
                 (projectile-current-project-files)
-                (concat name ".js"))))
+                :initial-input (concat name ".js"))))
     (find-file (expand-file-name file (projectile-project-root)))
     (run-hooks 'projectile-find-file-hook)))
```

**Comment by NicolasPetton** [comment]
Damien Cassou <notifications@github.com> writes:

> [This
> change](https://github.com/NicolasPetton/amd-mode.el/commit/d4396b72bd64ed6387be709e741b60f6434b062f#diff-cbed9aa7ffe6543e39332b37be5aa6f9R240)
> doesn't work with current stable version of projectile:

There's no stable tag/release for this yet, you should use the stable
version of amd-mode.el if you're using the stable version of projectile :)
